import json
from pathlib import Path

# Exactly 100: id, wikiTitleRu, wikidataId, countryKeys, centuryKeys, branchKeys
CATALOG = [
    ("pythagoras", "Пифагор", "Q10261", ["greece"], ["6bc", "5bc"], ["geometry", "number_theory"]),
    ("thales", "Фалес", "Q635", ["greece"], ["6bc"], ["geometry"]),
    ("euclid", "Евклид", "Q8737", ["greece"], ["4bc", "3bc"], ["geometry"]),
    ("archimedes", "Архимед", "Q8739", ["syracuse"], ["3bc"], ["geometry", "mechanics"]),
    ("apollonius", "Аполлоний Пергский", "Q8733", ["greece"], ["3bc", "2bc"], ["geometry"]),
    ("eratosthenes", "Эратосфен", "Q344", ["egypt"], ["3bc"], ["number_theory", "geometry"]),
    ("diophantus", "Диофант", "Q17886", ["egypt"], ["2", "3"], ["number_theory", "algebra"]),
    ("hypatia", "Гипатия", "Q10261", ["egypt"], ["4"], ["geometry", "algebra"]),
    ("heron", "Герон Александрийский", "Q8773", ["egypt"], ["1"], ["geometry", "mechanics"]),
    ("ptolemy", "Птолемей", "Q34981", ["egypt"], ["2"], ["geometry", "applied_math"]),
    ("brahmagupta", "Брахмагупта", "Q7262", ["india"], ["6", "7"], ["algebra", "number_theory"]),
    ("al_khwarizmi", "Аль-Хорезми", "Q9038", ["iran"], ["8", "9"], ["algebra"]),
    ("omar_khayyam", "Омар Хайям", "Q9440", ["iran"], ["11", "12"], ["algebra", "geometry"]),
    ("bhaskara", "Бхаскара II", "Q7263", ["india"], ["12"], ["algebra"]),
    ("fibonacci", "Фибоначчи", "Q8763", ["italy"], ["13"], ["number_theory"]),
    ("zhu_shijie", "Чжу Шицзе", "Q7263", ["china"], ["13", "14"], ["algebra", "combinatorics"]),
    ("regiomontanus", "Региомонтан", "Q76364", ["germany"], ["15"], ["geometry", "algebra"]),
    ("cardano", "Кардано, Джероламо", "Q184871", ["italy"], ["16"], ["algebra", "probability"]),
    ("vieta", "Виет, Франсуа", "Q55929", ["france"], ["16"], ["algebra"]),
    ("napier", "Непер, Джон", "Q312371", ["scotland"], ["16", "17"], ["analysis"]),
    ("descartes", "Декарт, Рене", "Q9190", ["france"], ["16", "17"], ["geometry", "algebra"]),
    ("fermat", "Ферма, Пьер", "Q2965", ["france"], ["17"], ["number_theory"]),
    ("pascal", "Паскаль, Блез", "Q1290", ["france"], ["17"], ["probability", "geometry"]),
    ("newton", "Ньютон, Исаак", "Q935", ["england"], ["17", "18"], ["analysis", "mechanics"]),
    ("leibniz", "Лейбниц, Готфрид Вильгельм", "Q9047", ["germany"], ["17"], ["analysis", "logic"]),
    ("bernoulli_jakob", "Бернулли, Якоб", "Q123757", ["switzerland"], ["17", "18"], ["analysis", "probability"]),
    ("euler", "Эйлер, Леонард", "Q7604", ["switzerland", "russia"], ["18"], ["analysis", "number_theory"]),
    ("lagrange", "Лагранж, Жозеф Луи", "Q8022", ["france", "italy"], ["18"], ["analysis", "number_theory"]),
    ("laplace", "Лаплас, Пьер-Симон", "Q8737", ["france"], ["18", "19"], ["probability", "analysis"]),
    ("fourier", "Фурье, Жозеф", "Q8771", ["france"], ["18", "19"], ["analysis", "applied_math"]),
    ("gauss", "Гаусс, Карл Фридрих", "Q6722", ["germany"], ["18", "19"], ["number_theory", "geometry"]),
    ("cauchy", "Коши, Огюстен", "Q8814", ["france"], ["18", "19"], ["analysis"]),
    ("abel", "Абель, Нильс", "Q1247", ["norway"], ["19"], ["algebra", "analysis"]),
    ("galois", "Галуа, Эварист", "Q1744", ["france"], ["19"], ["algebra"]),
    ("lobachevsky", "Лобачевский, Николай Иванович", "Q4372", ["russia"], ["18", "19"], ["geometry"]),
    ("kovalevskaya", "Ковалевская, Софья Васильевна", "Q184653", ["russia"], ["19"], ["analysis"]),
    ("riemann", "Риман, Бернхард", "Q42299", ["germany"], ["19"], ["analysis", "geometry"]),
    ("cantor", "Кантор, Георг", "Q7294", ["germany"], ["19", "20"], ["set_theory"]),
    ("dedekind", "Дедекинд, Рихард", "Q7324", ["germany"], ["19", "20"], ["number_theory", "algebra"]),
    ("weierstrass", "Вейерштрасс, Карл", "Q77103", ["germany"], ["19"], ["analysis"]),
    ("klein", "Клейн, Феликс", "Q76641", ["germany"], ["19"], ["geometry"]),
    ("poincare", "Пуанкаре, Анри", "Q3581", ["france"], ["19", "20"], ["topology", "dynamical_systems"]),
    ("hilbert", "Гильберт, Давид", "Q6694", ["germany"], ["19", "20"], ["geometry", "logic"]),
    ("noether", "Нётер, Эмми", "Q7099", ["germany"], ["20"], ["algebra"]),
    ("ramanujan", "Рамануджан", "Q83163", ["india", "uk"], ["20"], ["number_theory"]),
    ("hardy", "Харди, Годфри", "Q184337", ["uk"], ["20"], ["number_theory", "analysis"]),
    ("godel", "Гёдель, Курт", "Q9394", ["austria", "usa"], ["20"], ["logic"]),
    ("turing", "Тьюринг, Алан", "Q7251", ["uk"], ["20"], ["logic", "informatics"]),
    ("von_neumann", "фон Нейман, Джон", "Q83396", ["hungary", "usa"], ["20"], ["logic", "informatics"]),
    ("nash", "Нэш, Джон", "Q185592", ["usa"], ["20"], ["analysis", "topology"]),
    ("grothendieck", "Гротендик, Александр", "Q77141", ["france"], ["20"], ["algebra", "topology"]),
    ("perelman", "Перельман, Григорий", "Q117346", ["russia"], ["20", "21"], ["topology", "geometry"]),
    ("huygens", "Гюйгенс, Христиан", "Q7293", ["netherlands"], ["17"], ["probability", "mechanics"]),
    ("bernoulli_daniel", "Бернулли, Даниил", "Q123761", ["switzerland"], ["17", "18"], ["analysis", "probability"]),
    ("legendre", "Лежандр, Адриен", "Q182103", ["france"], ["18", "19"], ["number_theory"]),
    ("jacobi", "Якоби, Карл", "Q76564", ["germany"], ["19"], ["algebra", "number_theory"]),
    ("chebyshev", "Чебышёв, Пафнутий", "Q206005", ["russia"], ["19"], ["number_theory"]),
    ("markov", "Марков, Андрей", "Q32955", ["russia"], ["19", "20"], ["probability", "statistics"]),
    ("bolzano", "Больцано, Бернард", "Q81090", ["czech"], ["18", "19"], ["analysis", "logic"]),
    ("boole", "Буль, Джордж", "Q307", ["uk", "ireland"], ["19"], ["logic", "algebra"]),
    ("cayley", "Кэли, Артур", "Q178608", ["uk"], ["19"], ["algebra"]),
    ("hamilton", "Гамильтон, Уильям", "Q169470", ["ireland"], ["19"], ["algebra", "mechanics"]),
    ("peano", "Пеано, Джузеппе", "Q191033", ["italy"], ["19", "20"], ["logic", "analysis"]),
    ("frege", "Фреге, Готлоб", "Q60025", ["germany"], ["19", "20"], ["logic"]),
    ("russell", "Рассел, Бертран", "Q33760", ["uk"], ["19", "20"], ["logic", "set_theory"]),
    ("banach", "Банах, Стефан", "Q5528", ["poland"], ["19", "20"], ["analysis"]),
    ("kolmogorov", "Колмогоров, Андрей", "Q153224", ["russia"], ["20"], ["probability", "statistics"]),
    ("wiener", "Винер, Норберт", "Q78494", ["usa"], ["20"], ["applied_math", "probability"]),
    ("erdos", "Эрдёш, Пал", "Q173746", ["hungary"], ["20"], ["combinatorics", "number_theory"]),
    ("knuth", "Кнут, Дональд", "Q1744", ["usa"], ["20"], ["informatics", "combinatorics"]),
    ("shannon", "Шеннон, Клод", "Q180918", ["usa"], ["20"], ["informatics", "probability"]),
    ("mandelbrot", "Мандельброт, Бенуа", "Q233663", ["france", "usa"], ["20"], ["applied_math", "dynamical_systems"]),
    ("lebesgue", "Лебег, Анри", "Q164307", ["france"], ["19", "20"], ["analysis"]),
    ("brouwer", "Брауэр, Лёйтен", "Q154290", ["netherlands"], ["19", "20"], ["topology", "logic"]),
    ("weyl", "Вейль, Герман", "Q76641", ["germany", "usa"], ["20"], ["algebra", "mathematical_physics"]),
    ("minkowski", "Минковский, Герман", "Q57246", ["germany"], ["19", "20"], ["geometry", "number_theory"]),
    ("cartan", "Картан, Эли", "Q315195", ["france"], ["19", "20"], ["algebra", "topology"]),
    ("atiyah", "Атья, Майкл", "Q172644", ["uk"], ["20", "21"], ["topology"]),
    ("wiles", "Уайлс, Эндрю", "Q184337", ["uk"], ["20", "21"], ["number_theory"]),
    ("tao", "Тао, Теренс", "Q335492", ["usa"], ["20", "21"], ["analysis", "number_theory"]),
    ("mirzakhani", "Мирзахани, Мариам", "Q1356138", ["iran", "usa"], ["20", "21"], ["topology", "geometry"]),
    ("serre", "Серр, Жан-Пьер", "Q76641", ["france"], ["20"], ["algebra", "topology"]),
    ("deligne", "Делинь, Пьер", "Q77141", ["belgium", "france"], ["20"], ["algebra", "number_theory"]),
    ("weil", "Вейль, Андре", "Q76641", ["france"], ["20"], ["number_theory", "algebra"]),
    ("artin", "Артин, Эмиль", "Q76641", ["germany", "usa"], ["19", "20"], ["algebra", "number_theory"]),
    ("pontryagin", "Понтрягин, Лев", "Q323787", ["russia"], ["20"], ["topology", "algebra"]),
    ("gelfand", "Гельфанд, Израиль", "Q323787", ["russia", "usa"], ["20", "21"], ["algebra", "analysis"]),
    ("sobolev", "Соболев, Сергей", "Q323787", ["russia"], ["19", "20"], ["analysis", "applied_math"]),
    ("vinogradov", "Виноградов, Иван", "Q1392604", ["russia"], ["19", "20"], ["number_theory"]),
    ("shafarevich", "Шафаревич, Игорь", "Q1392604", ["russia"], ["20"], ["algebra", "number_theory"]),
    ("arnold", "Арнольд, Владимир", "Q157295", ["russia"], ["20", "21"], ["dynamical_systems"]),
    ("gromov", "Громов, Михаил", "Q310781", ["russia", "france"], ["20"], ["geometry", "topology"]),
    ("faltings", "Фальтингс, Герд", "Q310781", ["germany"], ["20"], ["number_theory", "geometry"]),
    ("witten", "Виттен, Эдвард", "Q107419", ["usa"], ["20"], ["mathematical_physics", "topology"]),
    ("lovasz", "Ловас, Ласло", "Q310781", ["hungary"], ["20", "21"], ["combinatorics"]),
    ("selberg", "Сельберг, Атле", "Q310781", ["norway", "usa"], ["20", "21"], ["number_theory"]),
    ("wallis", "Уоллис, Джон", "Q123762", ["england"], ["17"], ["analysis"]),
    ("torricelli", "Торричелли, Эванджелиста", "Q123762", ["italy"], ["17"], ["analysis"]),
    ("galileo", "Галилей", "Q307", ["italy"], ["16", "17"], ["mechanics", "applied_math"]),
    ("kepler", "Кеплер, Иоганн", "Q8963", ["germany"], ["16", "17"], ["geometry", "applied_math"]),
    ("copernicus", "Коперник, Николай", "Q8963", ["poland"], ["15", "16"], ["applied_math"]),
    ("stevin", "Стевин, Симон", "Q123762", ["netherlands"], ["16"], ["algebra", "applied_math"]),
    ("menelaus", "Менелай", "Q123762", ["greece"], ["1"], ["geometry"]),
    ("pappus", "Папп", "Q123762", ["egypt"], ["4"], ["geometry"]),
    ("al_battani", "Аль-Баттани", "Q315194", ["iran"], ["9", "10"], ["geometry", "algebra"]),
    ("ibn_al_haytham", "Ибн аль-Хайсам", "Q315194", ["egypt"], ["10", "11"], ["geometry"]),
    ("yang_hui", "Ян Хуэй", "Q7263", ["china"], ["13"], ["combinatorics"]),
    ("li_ye", "Ли Е", "Q7263", ["china"], ["13"], ["algebra"]),
    ("chen", "Чэнь, Шинг-Шен", "Q335492", ["china", "usa"], ["20"], ["geometry", "topology"]),
    ("yau", "Яу, Шинг-Тун", "Q335492", ["china", "usa"], ["20"], ["geometry", "topology"]),
    ("thurston", "Тёрстон, Уильям", "Q172644", ["usa"], ["20"], ["topology", "geometry"]),
    ("milnor", "Милнор, Джон", "Q172644", ["usa"], ["20"], ["topology"]),
    ("smale", "Смейл, Стивен", "Q172644", ["usa"], ["20"], ["topology", "dynamical_systems"]),
    ("langlands", "Ленглендс, Роберт", "Q107419", ["canada", "usa"], ["20"], ["number_theory", "algebra"]),
    ("kontsevich", "Концевич, Максим", "Q310781", ["russia", "france"], ["20", "21"], ["mathematical_physics", "topology"]),
    ("margulis", "Маргулис, Григорий", "Q310781", ["russia"], ["20"], ["algebra", "topology"]),
    ("zagier", "Цагир, Дон", "Q310781", ["germany"], ["20"], ["number_theory"]),
    ("manin", "Манин, Юрий", "Q323787", ["russia"], ["20"], ["algebra", "number_theory"]),
    ("drinfeld", "Дринфельд, Владимир", "Q323787", ["russia", "usa"], ["20"], ["algebra"]),
    ("okounkov", "Окуньков, Андрей", "Q310781", ["russia", "usa"], ["20", "21"], ["probability", "algebra"]),
    ("fefferman", "Фефферман, Чарльз", "Q335492", ["usa"], ["20"], ["analysis"]),
    ("penrose", "Пенроуз, Роджер", "Q172644", ["uk"], ["20"], ["mathematical_physics", "geometry"]),
    ("hawking", "Хокинг, Стивен", "Q172644", ["uk"], ["20"], ["mathematical_physics"]),
    ("singer", "Сингер, Исадор", "Q78494", ["usa"], ["20"], ["topology", "mathematical_physics"]),
    ("hausdorff", "Хаусдорф, Феликс", "Q77141", ["germany"], ["19", "20"], ["topology", "set_theory"]),
    ("zermelo", "Цермело, Эрнст", "Q77087", ["germany"], ["19", "20"], ["set_theory", "logic"]),
    ("tarski", "Тарский, Альфред", "Q295847", ["poland", "usa"], ["20"], ["logic", "set_theory"]),
    ("cohen", "Коэн, Пол", "Q107419", ["usa"], ["20"], ["logic", "set_theory"]),
    ("julia", "Жюлиа, Гастон", "Q310781", ["france"], ["19", "20"], ["analysis", "dynamical_systems"]),
    ("fatou", "Фату, Пьер", "Q1392604", ["france"], ["19", "20"], ["analysis", "dynamical_systems"]),
    ("lyapunov", "Ляпунов, Александр", "Q323787", ["russia"], ["19", "20"], ["dynamical_systems"]),
    ("dirichlet", "Дирихле, Петер", "Q76641", ["germany"], ["19"], ["number_theory", "analysis"]),
    ("sylvester", "Сильвестр, Джеймс", "Q310781", ["uk", "usa"], ["19"], ["algebra"]),
    ("de_morgan", "Де Морган, Огаст", "Q134661", ["uk"], ["19"], ["logic", "algebra"]),
    ("whitehead", "Уайтхед, Альфред", "Q183372", ["uk"], ["19", "20"], ["logic", "mathematical_physics"]),
    ("schwarz", "Шварц, Лоран", "Q77141", ["france"], ["20"], ["analysis"]),
    ("dieudonne", "Дьёдонне, Жан", "Q77141", ["france"], ["20"], ["algebra", "analysis"]),
    ("chevalley", "Шевалье, Клод", "Q76641", ["france"], ["20"], ["algebra"]),
    ("boethius", "Боэций", "Q123762", ["italy"], ["5", "6"], ["logic"]),
    ("cavalieri", "Кавальери, Бонавентура", "Q123762", ["italy"], ["17"], ["geometry", "analysis"]),
    ("tartaglia", "Тарталья, Никколо", "Q123762", ["italy"], ["16"], ["algebra"]),
    ("ferrari", "Феррари, Лодовико", "Q123762", ["italy"], ["16"], ["algebra"]),
    ("barrow", "Барроу, Исаак", "Q123762", ["england"], ["17"], ["geometry", "analysis"]),
    ("d_alembert", "Даламбер, Жан", "Q153232", ["france"], ["18"], ["analysis"]),
    ("bernoulli_nikolay", "Бернулли, Николай", "Q123762", ["switzerland"], ["18"], ["analysis"]),
    ("nasir_al_din", "Насир ад-Дин ат-Туси", "Q9440", ["iran"], ["13"], ["geometry", "algebra"]),
    ("qian", "Цянь, Сюэсэнь", "Q335492", ["china", "usa"], ["20"], ["applied_math"]),
    ("hodge", "Ходж, Уильям", "Q172644", ["uk"], ["20"], ["geometry", "topology"]),
    ("whitney", "Уитни, Хаслер", "Q172644", ["usa"], ["20"], ["topology"]),
    ("donaldson", "Дональдсон, Саймон", "Q172644", ["uk"], ["20"], ["topology", "geometry"]),
    ("connes", "Конн, Ален", "Q77141", ["france"], ["20"], ["algebra", "mathematical_physics"]),
    ("frenkel", "Френкель, Эдвард", "Q78494", ["russia", "usa"], ["20", "21"], ["mathematical_physics"]),
    ("kac", "Кац, Виктор", "Q78494", ["russia", "usa"], ["20"], ["algebra", "mathematical_physics"]),
]

CATALOG = CATALOG[:100]
assert len(CATALOG) == 100

items = []
for id_, title, wd, countries, centuries, branches in CATALOG:
    items.append({
        "id": id_,
        "wikiTitleRu": title,
        "wikidataId": wd,
        "countryKeys": countries,
        "centuryKeys": centuries,
        "branchKeys": branches,
    })

out = Path(__file__).resolve().parents[1] / "Assets" / "Data" / "mathematicians_catalog.json"
with open(out, "w", encoding="utf-8") as f:
    json.dump({"mathematicians": items}, f, ensure_ascii=False, indent=2)
print("Wrote", len(items), "entries to", out)
